version: "3.9"
services:
  nginx:
    build: ./docker/nginx/
    ports:
      - 80:80

    volumes:
      - ./:/var/www/html/

  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/

  db:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  mysql-data: